import bcryptjs from "bcryptjs";

interface SeedProduct {
  description: string;
  images: string[];
  inStock: number;
  price: number;
  sizes: ValidSizes[];
  slug: string;
  tags: string[];
  title: string;
  type: ValidTypes;
  gender: "men" | "women" | "kid" | "unisex";
}

interface SeedUser {
  email: string;
  password: string;
  name: string;
  role: "admin" | "user";
}

type ValidSizes = "XS" | "S" | "M" | "L" | "XL" | "XXL" | "XXXL";
type ValidTypes = "shirts" | "pants" | "hoodies" | "hats";

interface SeedData {
  categories: string[];
  products: SeedProduct[];
  users: SeedUser[];
}

interface SeedCountry {
  name: string;
  code: string;
  indicative: string;
}

export const initialData: SeedData = {
  categories: ["Shirts", "Pants", "Hoodies", "Hats"],
  users: [
    {
      email: "miguelangelfb19@utp.edu.co",
      name: "Miguel Angel Fernandez",
      password: bcryptjs.hashSync("miguel123"),
      role: "admin",
    },
    {
      email: "valengarzon0717@gmail.com",
      name: "Valentina Garzón",
      password: bcryptjs.hashSync("valen123"),
      role: "user",
    },
    {
      email: "prueba1@gmail.com",
      name: "Pepito Perez",
      password: bcryptjs.hashSync("pepito123"),
      role: "user",
    },
  ],
  products: [
    {
      description:
        "Introducing the Tesla Chill Collection. The Men’s Chill Crew Neck Sweatshirt has a premium, heavyweight exterior and soft fleece interior for comfort in any season. The sweatshirt features a subtle thermoplastic polyurethane T logo on the chest and a Tesla wordmark below the back collar. Made from 60% cotton and 40% recycled polyester.",
      images: ["1740176-00-A_0_2000.jpg", "1740176-00-A_1.jpg"],
      inStock: 7,
      price: 75,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "mens_chill_crew_neck_sweatshirt",
      type: "shirts",
      tags: ["sweatshirt"],
      title: "Men’s Chill Crew Neck Sweatshirt",
      gender: "men",
    },
    {
      description:
        "The Men's Quilted Shirt Jacket features a uniquely fit, quilted design for warmth and mobility in cold weather seasons. With an overall street-smart aesthetic, the jacket features subtle silicone injected Tesla logos below the back collar and on the right sleeve, as well as custom matte metal zipper pulls. Made from 87% nylon and 13% polyurethane.",
      images: ["1740507-00-A_0_2000.jpg", "1740507-00-A_1.jpg"],
      inStock: 5,
      price: 200,
      sizes: ["XS", "S", "M", "XL", "XXL"],
      slug: "men_quilted_shirt_jacket",
      type: "shirts",
      tags: ["jacket"],
      title: "Men's Quilted Shirt Jacket",
      gender: "men",
    },

    {
      description:
        "Introducing the Tesla Raven Collection. The Men's Raven Lightweight Zip Up Bomber has a premium, modern silhouette made from a sustainable bamboo cotton blend for versatility in any season. The hoodie features subtle thermoplastic polyurethane Tesla logos on the left chest and below the back collar, a concealed chest pocket with custom matte zipper pulls and a french terry interior. Made from 70% bamboo and 30% cotton.",
      images: ["1740250-00-A_0_2000.jpg", "1740250-00-A_1.jpg"],
      inStock: 10,
      price: 130,
      sizes: ["S", "M", "L", "XL", "XXL"],
      slug: "men_raven_lightweight_zip_up_bomber_jacket",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Raven Lightweight Zip Up Bomber Jacket",
      gender: "men",
    },

    {
      description:
        "Introducing the Tesla Turbine Collection. Designed for style, comfort and everyday lifestyle, the Men's Turbine Long Sleeve Tee features a subtle, water-based T logo on the left chest and our Tesla wordmark below the back collar. The lightweight material is double-dyed, creating a soft, casual style for ideal wear in any season. Made from 50% cotton and 50% polyester.",
      images: ["1740280-00-A_0_2000.jpg", "1740280-00-A_1.jpg"],
      inStock: 50,
      price: 45,
      sizes: ["XS", "S", "M", "L"],
      slug: "men_turbine_long_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Turbine Long Sleeve Tee",
      gender: "men",
    },
    {
      description:
        "Introducing the Tesla Turbine Collection. Designed for style, comfort and everyday lifestyle, the Men's Turbine Short Sleeve Tee features a subtle, water-based Tesla wordmark across the chest and our T logo below the back collar. The lightweight material is double-dyed, creating a soft, casual style for ideal wear in any season. Made from 50% cotton and 50% polyester.",
      images: ["1741416-00-A_0_2000.jpg", "1741416-00-A_1.jpg"],
      inStock: 50,
      price: 40,
      sizes: ["M", "L", "XL", "XXL"],
      slug: "men_turbine_short_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Turbine Short Sleeve Tee",
      gender: "men",
    },
    {
      description:
        "Designed for comfort, the Cybertruck Owl Tee is made from 100% cotton and features our signature Cybertruck icon on the back.",
      images: ["7654393-00-A_2_2000.jpg", "7654393-00-A_3.jpg"],
      inStock: 0,
      price: 35,
      sizes: ["M", "L", "XL", "XXL"],
      slug: "men_cybertruck_owl_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Cybertruck Owl Tee",
      gender: "men",
    },
    {
      description:
        "Inspired by our fully integrated home solar and storage system, the Tesla Solar Roof Tee advocates for clean, sustainable energy wherever you go. Designed for fit, comfort and style, the tee features an aerial view of our seamless Solar Roof design on the front with our signature T logo above 'Solar Roof' on the back. Made from 100% Peruvian cotton.",
      images: ["1703767-00-A_0_2000.jpg", "1703767-00-A_1.jpg"],
      inStock: 15,
      price: 35,
      sizes: ["S", "M", "L", "XL"],
      slug: "men_solar_roof_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Solar Roof Tee",
      gender: "men",
    },
    {
      description:
        "Inspired by the world’s most unlimited resource, the Let the Sun Shine Tee highlights our fully integrated home solar and storage system. Designed for fit, comfort and style, the tee features a sunset graphic along with our Tesla wordmark on the front and our signature T logo printed above 'Solar Roof' on the back. Made from 100% Peruvian cotton.",
      images: ["1700280-00-A_0_2000.jpg", "1700280-00-A_1.jpg"],
      inStock: 17,
      price: 35,
      sizes: ["XS", "S", "XL", "XXL"],
      slug: "men_let_the_sun_shine_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Let the Sun Shine Tee",
      gender: "men",
    },
    {
      description:
        "Designed for fit, comfort and style, the Men's 3D Large Wordmark Tee is made from 100% Peruvian cotton with a 3D silicone-printed Tesla wordmark printed across the chest.",
      images: ["8764734-00-A_0_2000.jpg", "8764734-00-A_1.jpg"],
      inStock: 12,
      price: 35,
      sizes: ["XS", "S", "M"],
      slug: "men_3d_large_wordmark_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's 3D Large Wordmark Tee",
      gender: "men",
    },
    {
      description:
        "Designed for fit, comfort and style, the Tesla T Logo Tee is made from 100% Peruvian cotton and features a silicone-printed T Logo on the left chest.",
      images: ["7652426-00-A_0_2000.jpg", "7652426-00-A_1.jpg"],
      inStock: 5,
      price: 35,
      sizes: ["XS", "S"],
      slug: "men_3d_t_logo_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's 3D T Logo Tee",
      gender: "men",
    },
    {
      description:
        "Designed for comfort and style in any size, the Tesla Small Wordmark Tee is made from 100% Peruvian cotton and features a 3D silicone-printed wordmark on the left chest.",
      images: ["8528839-00-A_0_2000.jpg", "8528839-00-A_2.jpg"],
      inStock: 2,
      price: 35,
      sizes: ["XS", "S", "M"],
      slug: "men_3d_small_wordmark_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men’s 3D Small Wordmark Tee",
      gender: "men",
    },
    {
      description:
        "Designed to celebrate Tesla's incredible performance mode, the Plaid Mode Tee features great fit, comfort and style. Made from 100% cotton, it's the next best thing to riding shotgun at the Nürburgring.",
      images: ["1549268-00-A_0_2000.jpg", "1549268-00-A_2.jpg"],
      inStock: 82,
      price: 35,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "men_plaid_mode_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Plaid Mode Tee",
      gender: "men",
    },
    {
      description:
        "Inspired by our popular home battery, the Tesla Powerwall Tee is made from 100% cotton and features the phrase 'Pure Energy' under our signature logo in the back. Designed for fit, comfort and style, the exclusive tee promotes sustainable energy in any environment.",
      images: ["9877034-00-A_0_2000.jpg", "9877034-00-A_2.jpg"],
      inStock: 24,
      price: 35,
      sizes: ["XL", "XXL"],
      slug: "men_powerwall_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Powerwall Tee",
      gender: "men",
    },
    {
      description:
        "Inspired by Tesla Battery Day and featuring the unveiled tabless battery cell, Battery Day Tee celebrates the future of energy storage and cell manufacturing. Designed for fit, comfort and style, Battery Day Tee is made from 100% cotton with a stylized cell printed across the chest. Made in Peru.",
      images: ["1633802-00-A_0_2000.jpg", "1633802-00-A_2.jpg"],
      inStock: 5,
      price: 30,
      sizes: ["XS", "S", "XXL"],
      slug: "men_battery_day_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Battery Day Tee",
      gender: "men",
    },
    {
      description:
        "Designed for exceptional comfort and inspired by the Cybertruck unveil event, the Cybertruck Bulletproof Tee is made from 100% cotton and features our signature Cybertruck icon on the back.",
      images: ["7654399-00-A_0_2000.jpg", "7654399-00-A_1.jpg"],
      inStock: 150,
      price: 30,
      sizes: ["M", "L"],
      slug: "men_cybertruck_bulletproof_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men’s Cybertruck Bulletproof Tee",
      gender: "men",
    },
    {
      description:
        "Inspired by the Model Y order confirmation graphic, the limited edition Haha Yes Tee is designed for comfort and style. Made from 100% Peruvian cotton and featuring the Tesla wordmark across the chest, the exclusive tee will commemorate your order for years to come.",
      images: ["7652410-00-A_0.jpg", "7652410-00-A_1_2000.jpg"],
      inStock: 10,
      price: 35,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "men_haha_yes_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Haha Yes Tee",
      gender: "men",
    },
    {
      description:
        "Designed for fit, comfort and style, the limited edition S3XY Tee is made from 100% cotton with a 3D silicone-printed “S3XY” logo across the chest. Made in Peru. Available in black.",
      images: ["8764600-00-A_0_2000.jpg", "8764600-00-A_2.jpg"],
      inStock: 34,
      price: 35,
      sizes: ["XS", "S", "M", "L"],
      slug: "men_s3xy_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's S3XY Tee",
      gender: "men",
    },
    {
      description:
        "Designed for fit, comfort and style, the Men's 3D Wordmark Long Sleeve Tee is made from 100% cotton and features an understated wordmark logo on the left chest.",
      images: ["8764813-00-A_0_2000.jpg", "8764813-00-A_1.jpg"],
      inStock: 15,
      price: 40,
      sizes: ["XL", "XXL"],
      slug: "men_3d_wordmark_long_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's 3D Wordmark Long Sleeve Tee",
      gender: "men",
    },
    {
      description:
        "Designed for fit, comfort and style, the Men's 3D T Logo Long Sleeve Tee is made from 100% cotton and features an understated T logo on the left chest.",
      images: ["8529198-00-A_0_2000.jpg", "8529198-00-A_1.jpg"],
      inStock: 12,
      price: 40,
      sizes: ["XS", "XXL"],
      slug: "men_3d_t_logo_long_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's 3D T Logo Long Sleeve Tee",
      gender: "men",
    },
    {
      description:
        "Introducing the Tesla Raven Collection. The Men's Raven Lightweight Hoodie has a premium, relaxed silhouette made from a sustainable bamboo cotton blend. The hoodie features subtle thermoplastic polyurethane Tesla logos across the chest and on the sleeve with a french terry interior for versatility in any season. Made from 70% bamboo and 30% cotton.",
      images: ["1740245-00-A_0_2000.jpg", "1740245-00-A_1.jpg"],
      inStock: 10,
      price: 115,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "men_raven_lightweight_hoodie",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Men's Raven Lightweight Hoodie",
      gender: "men",
    },
    {
      description:
        "Introducing the Tesla Chill Collection. The Chill Pullover Hoodie has a premium, heavyweight exterior and soft fleece interior for comfort in any season. The unisex hoodie features subtle thermoplastic polyurethane Tesla logos across the chest and on the sleeve, a double layer single seam hood and pockets with custom matte zipper pulls. Made from 60% cotton and 40% recycled polyester.",
      images: ["1740051-00-A_0_2000.jpg", "1740051-00-A_1.jpg"],
      inStock: 10,
      price: 130,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "chill_pullover_hoodie",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Chill Pullover Hoodie",
      gender: "unisex",
    },
    {
      description:
        "Introducing the Tesla Chill Collection. The Men's Chill Full Zip Hoodie has a premium, heavyweight exterior and soft fleece interior for comfort in any season. The hoodie features subtle thermoplastic polyurethane Tesla logos on the left chest and sleeve, a double layer single seam hood and pockets with custom matte zipper pulls. Made from 60% cotton and 40% recycled polyester.",
      images: ["1741111-00-A_0_2000.jpg", "1741111-00-A_1.jpg"],
      inStock: 100,
      price: 85,
      sizes: ["XS", "L", "XL", "XXL"],
      slug: "men_chill_full_zip_hoodie",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Chill Full Zip Hoodie",
      gender: "men",
    },
    {
      description:
        "Introducing the Tesla Chill Collection. The Men’s Chill Quarter Zip Pullover has a premium, heavyweight exterior and soft fleece interior for comfort in any season. The pullover features subtle thermoplastic polyurethane Tesla logos on the left chest and below the back collar, as well as a custom matte zipper pull. Made from 60% cotton and 40% recycled polyester.",
      images: ["1740140-00-A_0_2000.jpg", "1740140-00-A_1.jpg"],
      inStock: 7,
      price: 85,
      sizes: ["XS", "S", "M"],
      slug: "men_chill_quarter_zip_pullover_-_gray",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Chill Quarter Zip Pullover - Gray",
      gender: "men",
    },
    {
      description:
        "Introducing the Tesla Chill Collection. The Men’s Chill Quarter Zip Pullover has a premium, heavyweight exterior and soft fleece interior for comfort in any season. The pullover features subtle thermoplastic polyurethane Tesla logos on the left chest and below the back collar, as well as a custom matte zipper pull. Made from 60% cotton and 40% recycled polyester.",
      images: ["1740145-00-A_2_2000.jpg", "1740145-00-A_1.jpg"],
      inStock: 15,
      price: 85,
      sizes: ["XS", "S", "M", "L"],
      slug: "men_chill_quarter_zip_pullover_-_white",
      type: "shirts",
      tags: ["shirt"],
      title: "Men's Chill Quarter Zip Pullover - White",
      gender: "men",
    },
    {
      description:
        "The Unisex 3D Large Wordmark Pullover Hoodie features soft fleece and an adjustable, jersey-lined hood for comfort and coverage. Designed in a unisex style, the pullover hoodie includes a tone-on-tone 3D silicone-printed wordmark across the chest.",
      images: ["8529107-00-A_0_2000.jpg", "8529107-00-A_1.jpg"],
      inStock: 15,
      price: 70,
      sizes: ["XS", "S", "XL", "XXL"],
      slug: "3d_large_wordmark_pullover_hoodie",
      type: "hoodies",
      tags: ["hoodie"],
      title: "3D Large Wordmark Pullover Hoodie",
      gender: "unisex",
    },
    {
      description:
        "As with the iconic Tesla logo, the Cybertruck Graffiti Hoodie is a classic in the making. Unisex style featuring soft fleece and an adjustable, jersey-lined hood for comfortable coverage.",
      images: ["7654420-00-A_0_2000.jpg", "7654420-00-A_1_2000.jpg"],
      inStock: 13,
      price: 60,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "cybertruck_graffiti_hoodie",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Cybertruck Graffiti Hoodie",
      gender: "unisex",
    },
    {
      description:
        "The Relaxed T Logo Hat is a classic silhouette combined with modern details, featuring a 3D T logo and a custom metal buckle closure. The ultrasoft design is flexible and abrasion resistant, while the inner sweatband includes quilted padding for extra comfort and moisture wicking. The visor is fully made from recycled plastic bottles. 100% Cotton.",
      images: ["1657932-00-A_0_2000.jpg", "1657932-00-A_1.jpg"],
      inStock: 11,
      price: 30,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "relaxed_t_logo_hat",
      type: "hats",
      tags: ["hats"],
      title: "Relaxed T Logo Hat",
      gender: "unisex",
    },
    {
      description:
        "The Relaxed T Logo Hat is a classic silhouette combined with modern details, featuring a 3D T logo and a custom metal buckle closure. The ultrasoft design is flexible and abrasion resistant, while the inner sweatband includes quilted padding for extra comfort and moisture wicking. The visor is fully made from recycled plastic bottles. 100% Cotton.",
      images: ["1740417-00-A_0_2000.jpg", "1740417-00-A_1.jpg"],
      inStock: 13,
      price: 35,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "thermal_cuffed_beanie",
      type: "hats",
      tags: ["hats"],
      title: "Thermal Cuffed Beanie",
      gender: "unisex",
    },
    {
      description:
        "The Women's Cropped Puffer Jacket features a uniquely cropped silhouette for the perfect, modern style while on the go during the cozy season ahead. The puffer features subtle silicone injected Tesla logos below the back collar and on the right sleeve, custom matte metal zipper pulls and a soft, fleece lined collar. Made from 87% nylon and 13% polyurethane.",
      images: ["1740535-00-A_0_2000.jpg", "1740535-00-A_1.jpg"],
      inStock: 85,
      price: 225,
      sizes: ["XS", "S", "M"],
      slug: "women_cropped_puffer_jacket",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Women's Cropped Puffer Jacket",
      gender: "women",
    },
    {
      description:
        "Introducing the Tesla Chill Collection. The Women's Chill Half Zip Cropped Hoodie has a premium, soft fleece exterior and cropped silhouette for comfort in everyday lifestyle. The hoodie features an elastic hem that gathers at the waist, subtle thermoplastic polyurethane Tesla logos along the hood and on the sleeve, a double layer single seam hood and a custom ring zipper pull. Made from 60% cotton and 40% recycled polyester.",
      images: ["1740226-00-A_0_2000.jpg", "1740226-00-A_1.jpg"],
      inStock: 10,
      price: 130,
      sizes: ["XS", "S", "M", "XXL"],
      slug: "women_chill_half_zip_cropped_hoodie",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Women's Chill Half Zip Cropped Hoodie",
      gender: "women",
    },
    {
      description:
        "Introducing the Tesla Raven Collection. The Women's Raven Slouchy Crew Sweatshirt has a premium, relaxed silhouette made from a sustainable bamboo cotton blend. The slouchy crew features a subtle thermoplastic polyurethane Tesla wordmark on the left sleeve and a french terry interior for a cozy look and feel in every season. Pair it with your Raven Joggers or favorite on the go fit. Made from 70% bamboo and 30% cotton.",
      images: ["1740260-00-A_0_2000.jpg", "1740260-00-A_1.jpg"],
      inStock: 9,
      price: 110,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_raven_slouchy_crew_sweatshirt",
      type: "hoodies",
      tags: ["hoodie"],
      title: "Women's Raven Slouchy Crew Sweatshirt",
      gender: "women",
    },
    {
      description:
        "Introducing the Tesla Turbine Collection. Designed for style, comfort and everyday lifestyle, the Women's Turbine Cropped Long Sleeve Tee features a subtle, water-based Tesla wordmark across the chest and our T logo below the back collar. The lightweight material is double-dyed, creating a soft, casual style with a cropped silhouette. Made from 50% cotton and 50%",
      images: ["1740290-00-A_0_2000.jpg", "1740290-00-A_1.jpg"],
      inStock: 10,
      price: 45,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_turbine_cropped_long_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Women's Turbine Cropped Long Sleeve Tee",
      gender: "women",
    },
    {
      description:
        "ntroducing the Tesla Turbine Collection. Designed for style, comfort and everyday lifestyle, the Women's Turbine Cropped Short Sleeve Tee features a subtle, water-based Tesla wordmark across the chest and our T logo below the back collar. The lightweight material is double-dyed, creating a soft, casual style with a cropped silhouette. Made from 50% cotton and 50% polyester.",
      images: ["1741441-00-A_0_2000.jpg", "1741441-00-A_1.jpg"],
      inStock: 0,
      price: 40,
      sizes: ["XS", "S"],
      slug: "women_turbine_cropped_short_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Women's Turbine Cropped Short Sleeve Tee",
      gender: "women",
    },
    {
      description:
        "Designed for style and comfort, the ultrasoft Women's T Logo Short Sleeve Scoop Neck Tee features a tonal 3D silicone-printed T logo on the left chest. Made of 50% Peruvian cotton and 50% Peruvian viscose.",
      images: ["8765090-00-A_0_2000.jpg", "8765090-00-A_1.jpg"],
      inStock: 30,
      price: 35,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_t_logo_short_sleeve_scoop_neck_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Women's T Logo Short Sleeve Scoop Neck Tee",
      gender: "women",
    },
    {
      description:
        "Designed for style and comfort, the ultrasoft Women's T Logo Long Sleeve Scoop Neck Tee features a tonal 3D silicone-printed T logo on the left chest. Made of 50% Peruvian cotton and 50% Peruvian viscose.",
      images: ["8765100-00-A_0_2000.jpg", "8765100-00-A_1.jpg"],
      inStock: 16,
      price: 40,
      sizes: ["XS", "S", "L", "XL", "XXL"],
      slug: "women_t_logo_long_sleeve_scoop_neck_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Women's T Logo Long Sleeve Scoop Neck Tee",
      gender: "women",
    },
    {
      description:
        "Designed for style and comfort, the Women's Small Wordmark Short Sleeve V-Neck Tee features a tonal 3D silicone-printed wordmark on the left chest. Made of 100% Peruvian cotton.",
      images: ["8765120-00-A_0_2000.jpg", "8765120-00-A_1.jpg"],
      inStock: 18,
      price: 35,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_small_wordmark_short_sleeve_v-neck_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Women's Small Wordmark Short Sleeve V-Neck Tee",
      gender: "women",
    },
    {
      description:
        "Designed for style and comfort, the Women's Large Wordmark Short Sleeve Crew Neck Tee features a tonal 3D silicone-printed wordmark across the chest. Made of 100% Peruvian pima cotton.",
      images: ["8765115-00-A_0_2000.jpg", "8765115-00-A_1.jpg"],
      inStock: 5,
      price: 35,
      sizes: ["XL", "XXL"],
      slug: "women_large_wordmark_short_sleeve_crew_neck_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Women's Large Wordmark Short Sleeve Crew Neck Tee",
      gender: "women",
    },
    {
      description:
        "Designed to celebrate Tesla's incredible performance mode, the Plaid Mode Tee features great fit, comfort and style. Made from 100% cotton, it's the next best thing to riding shotgun at the Nürburgring.",
      images: ["1549275-00-A_0_2000.jpg", "1549275-00-A_1.jpg"],
      inStock: 16,
      price: 35,
      sizes: ["S", "M"],
      slug: "women_plaid_mode_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Women's Plaid Mode Tee",
      gender: "women",
    },
    {
      description:
        "Inspired by our popular home battery, the Tesla Powerwall Tee is made from 100% cotton and features the phrase 'Pure Energy' under our signature logo in the back. Designed for fit, comfort and style, the exclusive tee promotes sustainable energy in any",
      images: ["9877040-00-A_0_2000.jpg", "9877040-00-A_1.jpg"],
      inStock: 10,
      price: 130,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_powerwall_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Women’s Powerwall Tee",
      gender: "women",
    },
    {
      description:
        "Fully customized and uniquely styled, the Women's Corp Jacket features a silicone-printed 'T' logo on the left chest and prominent Tesla wordmark across the back.",
      images: ["5645680-00-A_0_2000.jpg", "5645680-00-A_3.jpg"],
      inStock: 3,
      price: 90,
      sizes: ["M", "L", "XL", "XXL"],
      slug: "women_corp_jacket",
      type: "shirts",
      tags: ["shirt"],
      title: "Women's Corp Jacket",
      gender: "women",
    },
    {
      description:
        "Introducing the Tesla Raven Collection. The Women's Raven Joggers have a premium, relaxed silhouette made from a sustainable bamboo cotton blend. The joggers feature a subtle thermoplastic polyurethane Tesla wordmark and T logo and a french terry interior for a cozy look and feel in every season. Pair them with your Raven Slouchy Crew Sweatshirt, Raven Lightweight Zip Up Jacket or other favorite on the go fit. Made from 70% bamboo and 30% cotton.",
      images: ["1740270-00-A_0_2000.jpg", "1740270-00-A_1.jpg"],
      inStock: 162,
      price: 100,
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      slug: "women_raven_joggers",
      type: "shirts",
      tags: ["shirt"],
      title: "Women's Raven Joggers",
      gender: "women",
    },
    {
      description:
        "Designed for fit, comfort and style, the Kids Cybertruck Graffiti Long Sleeve Tee features a water-based Cybertruck graffiti wordmark across the chest, a Tesla wordmark down the left arm and our signature T logo on the back collar. Made from 50% cotton and 50% polyester.",
      images: ["1742694-00-A_1_2000.jpg", "1742694-00-A_3.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S", "M"],
      slug: "kids_cybertruck_long_sleeve_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Kids Cybertruck Long Sleeve Tee",
      gender: "kid",
    },
    {
      description:
        "The Kids Scribble T Logo Tee is made from 100% Peruvian cotton and features a Tesla T sketched logo for every young artist to wear.",
      images: ["8529312-00-A_0_2000.jpg", "8529312-00-A_1.jpg"],
      inStock: 0,
      price: 25,
      sizes: ["XS", "S", "M"],
      slug: "kids_scribble_t_logo_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Kids Scribble T Logo Tee",
      gender: "kid",
    },
    {
      description:
        "The Kids Cybertruck Tee features the iconic Cybertruck graffiti wordmark and is made from 100% Peruvian cotton for maximum comfort.",
      images: ["8529342-00-A_0_2000.jpg", "8529342-00-A_1.jpg"],
      inStock: 10,
      price: 25,
      sizes: ["XS", "S", "M"],
      slug: "kids_cybertruck_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Kids Cybertruck Tee",
      gender: "kid",
    },
    {
      description:
        "The refreshed Kids Racing Stripe Tee is made from 100% Peruvian cotton, featuring a newly enhanced racing stripe with a brushed Tesla wordmark that's perfect for any speed racer.",
      images: ["8529354-00-A_0_2000.jpg", "8529354-00-A_1.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S", "M"],
      slug: "kids_racing_stripe_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Kids Racing Stripe Tee",
      gender: "kid",
    },
    {
      description:
        "Designed for fit, comfort and style, the Tesla T Logo Tee is made from 100% Peruvian cotton and features a silicone-printed T Logo on the left chest.",
      images: ["7652465-00-A_0_2000.jpg", "7652465-00-A_1.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S", "M"],
      slug: "kids_3d_t_logo_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Kids 3D T Logo Tee",
      gender: "kid",
    },
    {
      description:
        "The checkered tee is made from long grain, GMO free Peruvian cotton. Peru is the only country in the world where cotton is picked by hand on a large scale. The 4,500-year-old tradition prevents damage to the fiber during the picking process and removes the need to use chemicals to open the cotton plants before harvest. This environmentally friendly process results in cotton that is soft, strong, and lustrous – and the tee will get even softer with every wash.",
      images: ["100042307_0_2000.jpg", "100042307_alt_2000.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S", "M"],
      slug: "kids_checkered_tee",
      type: "shirts",
      tags: ["shirt"],
      title: "Kids Checkered Tee",
      gender: "kid",
    },
    {
      description:
        "For the future space traveler with discerning taste, a soft, cotton onesie with snap closure bottom. Clear labeling provided in case of contact with a new spacefaring civilization. 100% Cotton. Made in Peru",
      images: ["1473809-00-A_1_2000.jpg", "1473809-00-A_alt.jpg"],
      inStock: 16,
      price: 25,
      sizes: ["XS", "S"],
      slug: "made_on_earth_by_humans_onesie",
      type: "shirts",
      tags: ["shirt"],
      title: "Made on Earth by Humans Onesie",
      gender: "kid",
    },
    {
      description:
        "The Kids Scribble T Logo Onesie is made from 100% Peruvian cotton and features a Tesla T sketched logo for every little artist to wear.",
      images: ["8529387-00-A_0_2000.jpg", "8529387-00-A_1.jpg"],
      inStock: 0,
      price: 30,
      sizes: ["XS", "S"],
      slug: "scribble_t_logo_onesie",
      type: "shirts",
      tags: ["shirt"],
      title: "Scribble T Logo Onesie",
      gender: "kid",
    },
    {
      description:
        "Show your commitment to sustainable energy with this cheeky onesie for your young one. Note: Does not prevent emissions. 100% Cotton. Made in Peru.",
      images: ["1473834-00-A_2_2000.jpg", "1473829-00-A_2_2000.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S"],
      slug: "zero_emissions_(almost)_onesie",
      type: "shirts",
      tags: ["shirt"],
      title: "Zero Emissions (Almost) Onesie",
      gender: "kid",
    },
    {
      description:
        "Wear your Kids Cyberquad Bomber Jacket during your adventures on Cyberquad for Kids. The bomber jacket features a graffiti-style illustration of our Cyberquad silhouette and wordmark. With three zippered pockets and our signature T logo and Tesla wordmark printed along the sleeves, Kids Cyberquad Bomber Jacket is perfect for wherever the trail takes you. Made from 60% cotton and 40% polyester.",
      images: ["1742702-00-A_0_2000.jpg", "1742702-00-A_1.jpg"],
      inStock: 10,
      price: 65,
      sizes: ["XS", "S", "M"],
      slug: "kids_cyberquad_bomber_jacket",
      type: "shirts",
      tags: ["shirt"],
      title: "Kids Cyberquad Bomber Jacket",
      gender: "kid",
    },
    {
      description:
        "Cruise the playground in style with the Kids Corp Jacket. Modeled after the original Tesla Corp Jacket, the Kids Corp Jacket features the same understated style and high-quality materials but at a pint-sized scale.",
      images: ["1506211-00-A_0_2000.jpg", "1506211-00-A_1_2000.jpg"],
      inStock: 10,
      price: 30,
      sizes: ["XS", "S", "M"],
      slug: "kids_corp_jacket",
      type: "shirts",
      tags: ["shirt"],
      title: "Kids Corp Jacket",
      gender: "kid",
    },
  ],
};

export const countries: SeedCountry[] = [
  { name: "Afghanistan", code: "AFG", indicative: "+93" },
  { name: "Aland Islands", code: "ALA", indicative: "+358" },
  { name: "Albania", code: "ALB", indicative: "+355" },
  { name: "Alemania", code: "DEU", indicative: "+49" },
  { name: "Algeria", code: "DZA", indicative: "+213" },
  { name: "American Samoa", code: "ASM", indicative: "+1-684" },
  { name: "Andorra", code: "AND", indicative: "+376" },
  { name: "Angola", code: "AGO", indicative: "+244" },
  { name: "Anguilla", code: "AIA", indicative: "+1-264" },
  { name: "Antarctica", code: "ATA", indicative: "+672" },
  { name: "Antigua and Barbuda", code: "ATG", indicative: "+1-268" },
  { name: "Argentina", code: "ARG", indicative: "+54" },
  { name: "Armenia", code: "ARM", indicative: "+374" },
  { name: "Aruba", code: "ABW", indicative: "+297" },
  { name: "Australia", code: "AUS", indicative: "+61" },
  { name: "Austria", code: "AUT", indicative: "+43" },
  { name: "Azerbaijan", code: "AZE", indicative: "+994" },
  { name: "Bahamas", code: "BHS", indicative: "+1-242" },
  { name: "Bahrain", code: "BHR", indicative: "+973" },
  { name: "Bangladesh", code: "BGD", indicative: "+880" },
  { name: "Barbados", code: "BRB", indicative: "+1-246" },
  { name: "Belarus", code: "BLR", indicative: "+375" },
  { name: "Belgium", code: "BEL", indicative: "+32" },
  { name: "Belize", code: "BLZ", indicative: "+501" },
  { name: "Benin", code: "BEN", indicative: "+229" },
  { name: "Bermuda", code: "BMU", indicative: "+1-441" },
  { name: "Bhutan", code: "BTN", indicative: "+975" },
  { name: "Bielorrusia", code: "BLR", indicative: "+375" },
  { name: "Bolivia", code: "BOL", indicative: "+591" },
  { name: "Bosnia and Herzegovina", code: "BIH", indicative: "+387" },
  { name: "Botswana", code: "BWA", indicative: "+267" },
  { name: "Bouvet Island", code: "BVT", indicative: "+47" },
  { name: "Brazil", code: "BRA", indicative: "+55" },
  { name: "British Indian Ocean Territory", code: "IOT", indicative: "+246" },
  { name: "Brunei Darussalam", code: "BRN", indicative: "+673" },
  { name: "Bulgaria", code: "BGR", indicative: "+359" },
  { name: "Burkina Faso", code: "BFA", indicative: "+226" },
  { name: "Burundi", code: "BDI", indicative: "+257" },
  { name: "Cambodia", code: "KHM", indicative: "+855" },
  { name: "Cameroon", code: "CMR", indicative: "+237" },
  { name: "Canada", code: "CAN", indicative: "+1" },
  { name: "Cape Verde", code: "CPV", indicative: "+238" },
  { name: "Cayman Islands", code: "CYM", indicative: "+1-345" },
  { name: "Central African Republic", code: "CAF", indicative: "+236" },
  { name: "Chad", code: "TCD", indicative: "+235" },
  { name: "Chile", code: "CHL", indicative: "+56" },
  { name: "China", code: "CHN", indicative: "+86" },
  { name: "Christmas Island", code: "CXR", indicative: "+61" },
  { name: "Cocos (Keeling) Islands", code: "CCK", indicative: "+61" },
  { name: "Colombia", code: "COL", indicative: "+57" },
  { name: "Comoros", code: "COM", indicative: "+269" },
  { name: "Congo", code: "COG", indicative: "+242" },
  { name: "Congo, The Democratic Republic of the", code: "COD", indicative: "+243" },
  { name: "Cook Islands", code: "COK", indicative: "+682" },
  { name: "Costa Rica", code: "CRI", indicative: "+506" },
  { name: "Cote D'Ivoire", code: "CIV", indicative: "+225" },
  { name: "Croatia", code: "HRV", indicative: "+385" },
  { name: "Cuba", code: "CUB", indicative: "+53" },
  { name: "Cyprus", code: "CYP", indicative: "+357" },
  { name: "Czech Republic", code: "CZE", indicative: "+420" },
  { name: "Denmark", code: "DNK", indicative: "+45" },
  { name: "Djibouti", code: "DJI", indicative: "+253" },
  { name: "Dominica", code: "DMA", indicative: "+1-767" },
  { name: "Dominican Republic", code: "DOM", indicative: "+1-809" },
  { name: "Ecuador", code: "ECU", indicative: "+593" },
  { name: "Egypt", code: "EGY", indicative: "+20" },
  { name: "El Salvador", code: "SLV", indicative: "+503" },
  { name: "Equatorial Guinea", code: "GNQ", indicative: "+240" },
  { name: "Eritrea", code: "ERI", indicative: "+291" },
  { name: "Estonia", code: "EST", indicative: "+372" },
  { name: "Ethiopia", code: "ETH", indicative: "+251" },
  { name: "Falkland Islands (Malvinas)", code: "FLK", indicative: "+500" },
  { name: "Faroe Islands", code: "FRO", indicative: "+298" },
  { name: "Fiji", code: "FJI", indicative: "+679" },
  { name: "Finland", code: "FIN", indicative: "+358" },
  { name: "France", code: "FRA", indicative: "+33" },
  { name: "French Guiana", code: "GUF", indicative: "+594" },
  { name: "French Polynesia", code: "PYF", indicative: "+689" },
  { name: "French Southern Territories", code: "ATF", indicative: "+262" },
  { name: "Gabon", code: "GAB", indicative: "+241" },
  { name: "Gambia", code: "GMB", indicative: "+220" },
  { name: "Georgia", code: "GEO", indicative: "+995" },
  { name: "Germany", code: "DEU", indicative: "+49" },
  { name: "Ghana", code: "GHA", indicative: "+233" },
  { name: "Gibraltar", code: "GIB", indicative: "+350" },
  { name: "Greece", code: "GRC", indicative: "+30" },
  { name: "Greenland", code: "GRL", indicative: "+299" },
  { name: "Grenada", code: "GRD", indicative: "+1-473" },
  { name: "Guadeloupe", code: "GLP", indicative: "+590" },
  { name: "Guam", code: "GUM", indicative: "+1-671" },
  { name: "Guatemala", code: "GTM", indicative: "+502" },
  { name: "Guernsey", code: "GGY", indicative: "+44-1481" },
  { name: "Guinea", code: "GIN", indicative: "+224" },
  { name: "Guinea-Bissau", code: "GNB", indicative: "+245" },
  { name: "Guyana", code: "GUY", indicative: "+592" },
  { name: "Haiti", code: "HTI", indicative: "+509" },
  { name: "Heard Island and Mcdonald Islands", code: "HMD", indicative: "+672" },
  { name: "Holy See (Vatican City State)", code: "VAT", indicative: "+379" },
  { name: "Honduras", code: "HND", indicative: "+504" },
  { name: "Hong Kong", code: "HKG", indicative: "+852" },
  { name: "Hungary", code: "HUN", indicative: "+36" },
  { name: "Iceland", code: "ISL", indicative: "+354" },
  { name: "India", code: "IND", indicative: "+91" },
  { name: "Indonesia", code: "IDN", indicative: "+62" },
  { name: "Iran, Islamic Republic Of", code: "IRN", indicative: "+98" },
  { name: "Iraq", code: "IRQ", indicative: "+964" },
  { name: "Ireland", code: "IRL", indicative: "+353" },
  { name: "Isle of Man", code: "IMN", indicative: "+44-1624" },
  { name: "Israel", code: "ISR", indicative: "+972" },
  { name: "Italy", code: "ITA", indicative: "+39" },
  { name: "Jamaica", code: "JAM", indicative: "+1-876" },
  { name: "Japan", code: "JPN", indicative: "+81" },
  { name: "Jersey", code: "JEY", indicative: "+44-1534" },
  { name: "Jordan", code: "JOR", indicative: "+962" },
  { name: "Kazakhstan", code: "KAZ", indicative: "+7" },
  { name: "Kenya", code: "KEN", indicative: "+254" },
  { name: "Kiribati", code: "KIR", indicative: "+686" },
  { name: "Korea, Democratic People's Republic of", code: "PRK", indicative: "+850" },
  { name: "Korea, Republic of", code: "KOR", indicative: "+82" },
  { name: "Kuwait", code: "KWT", indicative: "+965" },
  { name: "Kyrgyzstan", code: "KGZ", indicative: "+996" },
  { name: "Lao People's Democratic Republic", code: "LAO", indicative: "+856" },
  { name: "Latvia", code: "LVA", indicative: "+371" },
  { name: "Lebanon", code: "LBN", indicative: "+961" },
  { name: "Lesotho", code: "LSO", indicative: "+266" },
  { name: "Liberia", code: "LBR", indicative: "+231" },
  { name: "Libyan Arab Jamahiriya", code: "LBY", indicative: "+218" },
  { name: "Liechtenstein", code: "LIE", indicative: "+423" },
  { name: "Lithuania", code: "LTU", indicative: "+370" },
  { name: "Luxembourg", code: "LUX", indicative: "+352" },
  { name: "Macao", code: "MAC", indicative: "+853" },
  {
    name: "Macedonia, The Former Yugoslav Republic of",
    code: "MKD",
    indicative: "+389",
  },
  { name: "Madagascar", code: "MDG", indicative: "+261" },
  { name: "Malawi", code: "MWI", indicative: "+265" },
  { name: "Malaysia", code: "MYS", indicative: "+60" },
  { name: "Maldives", code: "MDV", indicative: "+960" },
  { name: "Mali", code: "MLI", indicative: "+223" },
  { name: "Malta", code: "MLT", indicative: "+356" },
  { name: "Marshall Islands", code: "MHL", indicative: "+692" },
  { name: "Martinique", code: "MTQ", indicative: "+596" },
  { name: "Mauritania", code: "MRT", indicative: "+222" },
  { name: "Mauritius", code: "MUS", indicative: "+230" },
  { name: "Mayotte", code: "MYT", indicative: "+262" },
  { name: "Mexico", code: "MEX", indicative: "+52" },
  { name: "Micronesia (Federated States of)", code: "FSM", indicative: "+691" },
  { name: "Moldova", code: "MDA", indicative: "+373" },
  { name: "Monaco", code: "MCO", indicative: "+377" },
  { name: "Mongolia", code: "MNG", indicative: "+976" },
  { name: "Montenegro", code: "MNE", indicative: "+382" },
  { name: "Montserrat", code: "MSR", indicative: "+1-664" },
  { name: "Morocco", code: "MAR", indicative: "+212" },
  { name: "Mozambique", code: "MOZ", indicative: "+258" },
  { name: "Myanmar", code: "MMR", indicative: "+95" },
  { name: "Namibia", code: "NAM", indicative: "+264" },
  { name: "Nauru", code: "NRU", indicative: "+674" },
  { name: "Nepal", code: "NPL", indicative: "+977" },
  { name: "Netherlands", code: "NLD", indicative: "+31" },
  { name: "New Caledonia", code: "NCL", indicative: "+687" },
  { name: "New Zealand", code: "NZL", indicative: "+64" },
  { name: "Nicaragua", code: "NIC", indicative: "+505" },
  { name: "Niger", code: "NER", indicative: "+227" },
  { name: "Nigeria", code: "NGA", indicative: "+234" },
  { name: "Niue", code: "NIU", indicative: "+683" },
  { name: "Norfolk Island", code: "NFK", indicative: "+672" },
  { name: "Northern Mariana Islands", code: "MNP", indicative: "+1-670" },
  { name: "Norway", code: "NOR", indicative: "+47" },
  { name: "Oman", code: "OMN", indicative: "+968" },
  { name: "Pakistan", code: "PAK", indicative: "+92" },
  { name: "Palau", code: "PLW", indicative: "+680" },
  { name: "Panama", code: "PAN", indicative: "+507" },
  { name: "Papua New Guinea", code: "PNG", indicative: "+675" },
  { name: "Paraguay", code: "PRY", indicative: "+595" },
  { name: "Peru", code: "PER", indicative: "+51" },
  { name: "Philippines", code: "PHL", indicative: "+63" },
  { name: "Pitcairn", code: "PCN", indicative: "+64" },
  { name: "Poland", code: "POL", indicative: "+48" },
  { name: "Portugal", code: "PRT", indicative: "+351" },
  { name: "Puerto Rico", code: "PRI", indicative: "+1-787" },
  { name: "Qatar", code: "QAT", indicative: "+974" },
  { name: "Romania", code: "ROU", indicative: "+40" },
  { name: "Russian Federation", code: "RUS", indicative: "+7" },
  { name: "Rwanda", code: "RWA", indicative: "+250" },
  { name: "Reunion", code: "REU", indicative: "+262" },
  { name: "Saint Barthelemy", code: "BLM", indicative: "+590" },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    code: "SHN",
    indicative: "+290",
  },
  { name: "Saint Kitts and Nevis", code: "KNA", indicative: "+1-869" },
  { name: "Saint Lucia", code: "LCA", indicative: "+1-758" },
  { name: "Saint Martin", code: "MAF", indicative: "+590" },
  { name: "Saint Pierre and Miquelon", code: "SPM", indicative: "+508" },
  { name: "Saint Vincent and the Grenadines", code: "VCT", indicative: "+1-784" },
  { name: "Samoa", code: "WSM", indicative: "+685" },
  { name: "San Marino", code: "SMR", indicative: "+378" },
  { name: "Sao Tome and Principe", code: "STP", indicative: "+239" },
  { name: "Saudi Arabia", code: "SAU", indicative: "+966" },
  { name: "Senegal", code: "SEN", indicative: "+221" },
  { name: "Serbia", code: "SRB", indicative: "+381" },
  { name: "Seychelles", code: "SYC", indicative: "+248" },
  { name: "Sierra Leone", code: "SLE", indicative: "+232" },
  { name: "Singapore", code: "SGP", indicative: "+65" },
  { name: "Sint Maarten", code: "SXM", indicative: "+1-721" },
  { name: "Slovakia", code: "SVK", indicative: "+421" },
  { name: "Slovenia", code: "SVN", indicative: "+386" },
  { name: "Solomon Islands", code: "SLB", indicative: "+677" },
  { name: "Somalia", code: "SOM", indicative: "+252" },
  { name: "South Africa", code: "ZAF", indicative: "+27" },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "SGS",
    indicative: "+500",
  },
  { name: "South Sudan", code: "SSD", indicative: "+211" },
  { name: "Spain", code: "ESP", indicative: "+34" },
  { name: "Sri Lanka", code: "LKA", indicative: "+94" },
  { name: "Sudan", code: "SDN", indicative: "+249" },
  { name: "Suriname", code: "SUR", indicative: "+597" },
  { name: "Svalbard and Jan Mayen", code: "SJM", indicative: "+47" },
  { name: "Sweden", code: "SWE", indicative: "+46" },
  { name: "Switzerland", code: "CHE", indicative: "+41" },
  { name: "Syrian Arab Republic", code: "SYR", indicative: "+963" },
  { name: "Taiwan", code: "TWN", indicative: "+886" },
  { name: "Tajikistan", code: "TJK", indicative: "+992" },
  { name: "Tanzania", code: "TZA", indicative: "+255" },
  { name: "Thailand", code: "THA", indicative: "+66" },
  { name: "Timor-Leste", code: "TLS", indicative: "+670" },
  { name: "Togo", code: "TGO", indicative: "+228" },
  { name: "Tokelau", code: "TKL", indicative: "+690" },
  { name: "Tonga", code: "TON", indicative: "+676" },
  { name: "Trinidad and Tobago", code: "TTO", indicative: "+1-868" },
  { name: "Tunisia", code: "TUN", indicative: "+216" },
  { name: "Turkey", code: "TUR", indicative: "+90" },
  { name: "Turkmenistan", code: "TKM", indicative: "+993" },
  { name: "Tuvalu", code: "TUV", indicative: "+688" },
  { name: "Uganda", code: "UGA", indicative: "+256" },
  { name: "Ukraine", code: "UKR", indicative: "+380" },
  { name: "United Arab Emirates", code: "ARE", indicative: "+971" },
  { name: "United Kingdom", code: "GBR", indicative: "+44" },
  { name: "United States", code: "USA", indicative: "+1" },
  { name: "Uruguay", code: "URY", indicative: "+598" },
  { name: "Uzbekistan", code: "UZB", indicative: "+998" },
  { name: "Vanuatu", code: "VUT", indicative: "+678" },
  { name: "Venezuela", code: "VEN", indicative: "+58" },
  { name: "Viet Nam", code: "VNM", indicative: "+84" },
  { name: "Western Sahara", code: "ESH", indicative: "+212" },
  { name: "Yemen", code: "YEM", indicative: "+967" },
  { name: "Zambia", code: "ZMB", indicative: "+260" },
  { name: "Zimbabwe", code: "ZWE", indicative: "+263" },
];



